name: Continuous Delivery

on:
  push:
    branches:
      - main
      - ci/publish

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install
        run: |
          npm ci
          npm ls

      - name: "Continuous Integration: lint"
        run: |
          npm run lint --if-present

      - name: "Continuous Integration: build"
        run: |
          npm run build --if-present
          npm run build --if-present --workspaces

      - name: "Continuous Integration: test"
        run: |
          npm run test --if-present

      - name: "Continuous Integration: create baseline for visual regression test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          npx lerna run percy-snapshot

      - name: Continuous Deployment to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: packages/storybook/dist

      - name: Continuous Deployment to GitHub repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "NL Design System"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "NL Design System"
        run: |
          npm run version -- --yes

      - name: Continuous Deployment to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_TOKEN}"
          npm run publish -- --no-verify-access --yes
          npm config delete "//registry.npmjs.org/:_authToken"
